project:
  type: website
  output-dir: docs

website:
  title: "žuk nach Georgien"
  description: "Das ist mein Blog über mein Auslandsstudienjahr in Tbilisi, Georgien."
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/apfelpfluecker
      #- icon: twitter
      #  href: https://twitter.com
      - icon: youtube
        href: https://www.youtube.com/channel/UCxiXYviRajihSzyp8eSgxmA
      - archive.qmd
format:
  html:
    theme: theme.scss
    css: styles.css

editor: visual

lang: de

