project:
  type: website
  resources:
    - "CNAME"

website:
  title: "žuk nach Georgien"
  description: "Das ist mein Blog über mein Auslandsstudienjahr in Tbilisi, Georgien."
  site-url: "https://blog.zukarton.eu"
  navbar:
    collapse: false
    left: 
      - text: Blog
        href: blog.qmd
      - text: Lieder
        href: lieder.qmd
      - text: Archiv
        href: archive.qmd
    right:
      - icon: music-note-list
        href: https://liederpool-projekt.github.io/how-to-liederbuch/
      #- icon: twitter
      #  href: https://twitter.com
      - icon: youtube
        href: https://www.youtube.com/@Katzenrunde
      - icon: rss
        href: blog.xml
  page-footer: 
    left: "Made with [Quarto](https://quarto.org)."
    center: "© žuk, 2025"
    right:
      - icon: music-note-list
        href: https://liederpool-projekt.github.io/how-to-liederbuch/
      - icon: youtube
        href: https://www.youtube.com/@Katzenrunde
      - icon: rss
        href: blog.xml

format:
  html:
    theme: theme.scss
    css: styles.css
    link-external-newwindow: true

#resources: 
#  - CNAME # https://github.com/quarto-dev/quarto-cli/discussions/3249

editor: visual

lang: de

pagetitle: "{{< meta title >}} | žuk nach Georgien"
author-meta: "žuk"

