---
title: "Abschiedskonzert von Nele und mir am 06.09."
author: "žuk und Nele"
date: "2024-08-05"
description: "Wir verlassen Marburg und wollen vorher nochmal eine schöne Zeit mit euch haben. Deshalb spielen wir ein Konzert in Marburg am 06.09. Kommt gerne rum..."
categories: [News]
---

Hallo zusammen,

nach einigen beziehungsweise sehr vielen Jahren verlassen wir Marburg. Nele geht zum Studieren nach Göttingen, žuk zieht es für ein Jahr nach Georgien. Zum Abschied wollen wir nochmal einen Anlass bereiten, sich zu sehen und eine schöne Zeit zusammen zu haben. Und wie ginge das schöner als mit einem sommerlichen Konzert mit anschließendem Beisammensein und Musizieren? Also: Zückt die Terminkalender und malt euch den 06.09. ganz fett rot in den Kalender. Das Konzert wird vermutlich am frühen Abend stattfinden, der Ort steht noch nicht fest, wird aber rechtzeitig noch verkündet. Wir spielen eine Handvoll Songs, die wir sehr toll finden und mit denen wir schöne Momente und Situationen verbinden. Kommt sehr gerne rum! Im Anschluss wollen wir zusammen essen (bringt bitte etwas für ein Bring-and-share-Buffet mit) und dann gibt es Möglichkeiten zu quatschen oder zu singen. Wem das Konzept Singerunde nicht vertraut ist, kann einfach zum Quatschen & Essen bleiben. Für etwaige Übernachtungsmöglichkeiten wird gesorgt sein.

Eine Anmeldung soll zwar nicht obligatorisch sein, hilft uns aber sehr beim Planen! Also wenn ihr wisst, ob ihr kommt, sagt gern Bescheid!

Liebe Grüße und bis bald!\
Nele und žuk

------------------------------------------------------------------------

Infos kurz & knapp:

-   Konzert am 06.09. ab abends

-   anschließend Bring & Share Buffet (→ dafür etwas mitbringen)

-   danach Singen und Quatschen

-   Übernachtungsmöglichkeiten vorhanden

------------------------------------------------------------------------

**Neue Infos:**

Ihr könnt **ab 18.30 Uhr** kommen. Im Anschluss ans Ankommen wird das Buffet eröffnet. **Start des Konzerts ist ca. 20 Uhr.** Wir wollen, dass möglichst alle dabei sein können.

Es war sehr schwierig, eine Location zu finden, aber wir haben nun einen ganz wundervollen Ort, leider etwas auswärts von Marburg. Wir feiern im **Brunnenweg 16, 35274 Kirchhain-Stausebach**. Ihr kommt dort sehr gut mit der Bahn nach Kirchhain (von Marburg 8 Minuten mit RE). Alle Regiozüge zwischen Kassel-Marburg-Frankfurt fahren über Kirchhain. Von Kirchhain aus, kann man entweder Rad fahren (ca. 4 km), ein AST nehmen (alle zwei Stunden, u.a. 17.34 und 19.34) oder ihr lasst euch von uns shutteln. Gebt dazu gern über unsere Nuudel-Umfrage Bescheid, wann ihr ankommt: <https://nuudel.digitalcourage.de/O1528AZqLVVQGhBL>. Neles Handynummer findet ihr für spontane Notwendigkeiten dort auch. Laufen würden wir nicht empfehlen, da ist man ne Stunde unterwegs. Geparkt werden kann dort auf dem Hof.

Denkt bitte an einen **Beitrag zum Bring-and-share-Buffet**, gern vegetarisch/vegan. Sowohl Herzhaftes als auch Süßes ist gern gesehen.\
**Bringt bitte auch Besteck und Behältnisse (Koschi) mit.**

Geschlafen werden kann auf dem großen Scheunenboden, deckt euch also entsprechend ein (Schlafsack/Isomatte).

Wenn irgendjemand Jockel Bescheid sagen könnte, wo es stattfindet, hilft das sicher sehr ;)
