---
title: "Zwischen den Jahren"
author: "žuk"
date: "2025-01-03"
categories: [News]
image: ""
description: ""
draft: true
---

## Aktuelle Empfehlungen

-   Alles in mir will hier unbedingt (wieder) Alin Coen unterbringen, aber ich kann eigentlich nicht jede Woche dasselbe empfehlen… Ich hab jedenfalls Alin wieder sehr viel im Ohr gehabt und völlig zurecht auf jeden Fall.
-   Ich hab ja schon von milou & flint erzählt und ich fürchte, ich muss euch noch zwei weitere Lieder empfehlen, weil die so toll sind. Einmal [„Excuse-moi“](https://www.youtube.com/watch?v=wN-5sFGJv0A) und dann [„Schwalben Anfang Mai“](https://www.youtube.com/watch?v=XxClhVDCE-8). Genießt es.
-   Wen ich auch etwas wiederentdeckt habe, ist Max Prosa. Der hat ein ganz tolles Lied geschrieben: [„Vier Leben“](https://www.youtube.com/watch?v=EITBWNSZJaA).
-   Dota kennen bestimmt viele von euch, aber [„Dein Haar“](https://www.youtube.com/watch?v=-R_kyi919ug) ist sehr unbekannt – zu Unrecht, wie ich finde. Der Grund ist vermutlich, dass es ein (ausschließlich digital erschienener) Bonus Track ist, den ich vor einiger Zeit mal entdeckt hatte. Er startet ganz Dota-untypisch und das Vorspiel erinnert mich sehr an ein anderes, ganz anderes, aber auch sehr tolles Lied aus der Serie „Babylon Berlin“. Es heißt [„Du bist alles“](https://www.youtube.com/watch?v=4Gf9Tzmyxis) und in der Serie wird es von einem schwulen Fotografen gesungen, der ein äußerst sympathischer Typ ist. Tobias Morgenstern spielt das Akkordeon, so zum Dahinschmelzen…
-   Und jetzt hätte ich’s fast vergessen, aber: Die „Lage der Nation“ (also Philip Banse und Ulf Buermeyer) waren zu Gast im Podcast [„Alles gesagt“](https://www.zeit.de/politik/2024-12/lage-der-nation-interviewpodcast-alles-gesagt), dem Podcast der ZEIT, der erst endet, wenn der\*die Gast\*in das möchte. Ich hatte recht viel Zeit, als ich krank war und es ist sehr interessant.
