---
title: "Achtung, wir unterbrechen die Sendung für eine kurze politische Mitteilung. Die nachfolgenden Sendungen verschieben sich um einen Blogartikel."
author: "žuk"
date: "2024-10-09"
categories: [Georgien, News]
image: ""
description: ""
draft: true
---

Mittlerweile ist schon wieder etwas Zeit seit dem Thüringen-Eklat vergangen, aber es lässt mich nicht los, was politisch in Deutschland gerade los ist. Woher kommt bitte diese Migrationsdebatte?

Ich habe keine Kapazität, hier eine ausführliche Argumentation hinzulegen, warum es der empirischen Realität widerspricht, dass die Ausländerkriminalität zunähme (beziehungsweise um genau zu sein widersprechen alle darauf fußenden Argumentationen dieser Realität). Das haben andere schon sehr ausführlich dargelegt.[^1] Die „Migrationsdebatte“ ist eine solche Nebelkerze und ich verstehe absolut nicht, warum alle relevanten politischen Parteien darauf so anspringen. Letztendlich hilft die Dramatisierung dieses Themas nur einer Partei: der AfD.[^2]

[^1]: Siehe [Lage der Nation 395](https://lagedernation.org/podcast/ldn395-wahlen-in-thueringen-und-sachsen-ursachen-fuer-den-erfolg-der-afd-im-osten-interview-steffen-mau-soziologe-union-und-migration-argumente-gegen-afd-thesen-klimawandel-veraendert-staedte/), Kapitel „Union: Das komplexe Wesen des Themas ‚Migration‘“, „Terror: Solingen und die politische Reaktion“, „Migration: Das Maßnahmen-Paket und die Suche nach Kontrolle“, „Migration: Kann Deutschland Geflüchtete an seinen Grenzen zurückweisen?“. Siehe [Lage der Nation 397](https://lagedernation.org/podcast/tv-duell-harris-vs-trump-krise-bei-volkswagen-neue-e-auto-foerderung-grenzkontrollen-an-deutschen-aussengrenzen-nahost-reise-mit-aussenministerin-deutsche-israel-politik-interview-annalena-baer/), Kapitel „Migration: Ampel will ab 16.9. Grenzen dicht machen“, „Migration: Union lässt Gespräche mit der Ampel platzen“. Siehe [Lage der Nation 398](https://lagedernation.org/podcast/ldn398-grenzkontrollen-in-frankfurt-oder-merz-wird-cdu-kanzlerkandidat-explodierende-pager-und-funkgeraete-im-libanon-darknet-geknackt-kollaps-der-carolabruecke-ampel-plant-riester-reform-feedba/), Kapitel „Grenzkontrollen: Löchrige Grenzen in der ganzen Republik“. Siehe [Lage der Nation 399](https://lagedernation.org/podcast/ldn399-landtagswahl-brandenburg-ruecktritt-der-gruenen-spitze-ist-scholz-der-richtige-kandidat-exit-plaene-der-fdp-autoindustrie-gegen-co2-grenzwerte-sicherheitspaket-im-bundestag-slapp-studie/), Kapitel „Terror-Reaktion: Ampel streitet über Migrations- und Sicherheitspaket“.

[^2]: Falls irgendjemand mit der Polizeilichen Kriminalstatistik (PKS) rumkommen will. Da dreht sich mir als Sozialwissenschaftler der Magen um. Wer so inkompetent mit Statistik umgeht, sollte nicht verbeamtet sein. Mai Thi Nguyen-Kim hat einige wichtige Punkte mal sehr gut erklärt: [Link](https://www.youtube.com/watch?v=FGAyYl3ZICw).

Und damit wären wir beim nächsten Thema: Thüringen. Sicherlich habt ihr vom Eklat im Thüringer Landtag mitbekommen (wer nicht, der tauche [hier](https://www.tagesschau.de/inland/faq-thueringen-verfassungsgerichtshof-urteil-100.html) tiefer ein). Dass es zu einem Eklat kommt, kam allerdings gar nicht unerwartet, denn die CDU hat sich im Jahr vor der Landtagswahl dagegen gewehrt, die Geschäftsordnung des Landtags so zu ändern, dass die AfD gar nicht die Möglichkeit hat, den Parlamentarismus so vorzuführen. Versteht mich nicht falsch, ich möchte nicht die AfD mit der CDU vergleichen – das wäre absurd. Aber diese Partei schadet unserer Demokratie und unserem Land, weil sie sich – anstatt sich mit den realen Problemen fast ausschließlich mit Schattenproblemen auseinandersetzt. Migration. Keine Regierung mit den Grünen (mindestens genauso absurd). Die Institutionen der Demokratie nicht vor den Rechtsextremist\*innen schützen. Man muss die Politik der Ampel-Regierung nicht gut finden (da tue ich mich auch sehr schwer), aber die der Union will ich diesem Land nicht zumuten. Leider gibt es keine glänzenden Alternativen. Das Bündnis Sarah Wagenknecht ist mindestens ebenso populistisch und realitätsfern in Bezug auf gute Lösungsansätze unserer Probleme. Dabei braucht es gute Lösungsansätze – schade nur, dass sich keine Partei darum zu kümmern scheint.

Warum ich das hier schreibe: Politik ist nicht einfach, sondern unglaublich kompliziert. Dass die AfD eine Gefahr für unsere Demokratie vorstellt, ist uns allen klar. Ich denke aber, dass das – wenn auch in anderem Maß – auch für andere Parteien gilt. BSW. CDU. Nächstes Jahr ist Bundestagswahl und es ist natürlich wichtig, wählen zu gehen. Und auch wenn das schwerfällt, bleibt wohl nichts anderes, das geringste Übel zu wählen, eine schlagkräftige Alternative ist (für mich) nicht in Sicht. Aber bitte wählt nicht die CDU oder BSW.

Zuletzt habe ich noch einen Buchtipp: Steffen Mau et al. haben vor einem knappen Jahr in einer vom Schreibstil her sehr zugänglichen Studie dargelegt, warum unsere Gesellschaft gar nicht so sehr gespalten ist und welche Themengruppierungen jedoch diesen Anschein erwecken. Es lohnt sich sehr und ist aktuell (noch) in der Auflage von der bpb für 7 € zu erhalten ([Link](https://www.bpb.de/shop/buecher/schriftenreihe/551980/triggerpunkte/)), sonst im Buchhandel eures Vertrauens für 25 € ([Link](https://www.suhrkamp.de/buch/triggerpunkte-t-9783518029848)). Tatsächlich habe ich die Theoriebasis dieser Studie auch für meine Bachelorarbeit über die Polarisierung geschlechtergerechter Sprache genutzt, in der ich unter anderem populistische Äußerungen zu diesem Thema auf Facebook bei der AfD und der CSU nachweisen konnte. Aber das ist ein anderes Thema.
