---
title: "Rückreise Tag 4: Von irgendwo in der Türkei über Ankara nach Istanbul"
author: "žuk"
date: "2025-08-"
categories: [Georgien, News]
image: ""
description: ""
draft: true
---

Noch fünf Stunden Schlaf bekomme ich an dem Morgen. Als ich einschlafe, dämmert es schon. Ich bin schon sehr gerädert von der Nacht. Schade, ich hatte mich wirklich auf eine Nacht im Schlafwagen gefreut. Das kommt dann wohl erst noch. Die letzten Kilometer genieße ich noch das Rausschauen. Es ist jetzt 11.31 Uhr, wir haben also schon anderthalb Stunden Verspätung. Währenddessen fängt mein Bauch etwas an zu grummeln, so richtig fit fühle ich mich nicht. Um 13 Uhr kommen wir dann in Ankara an. Jetzt wird es doch etwas knapp für den Bus, den ich mir für 14 Uhr nach Istanbul gebucht hatte. Glücklicherweise hilft mir der armenische Türke zum richtigen Metro-Eingang. Mit der Linie A1 geht’s zum zentralen Omnibusbahnhof Ankara. Dort angekommen, stellt sich mir wie an quasi allen Busbahnhöfen die Frage, warum die es nicht schaffen, ihre Informationen leicht und einfach zugänglich zu machen. Ich muss zum Büro des Busunternehmens, um das „Gleis“ herauszufinden, auf dem mein Bus abfährt.

Aber es klappt alles und meine sechseinhalbstündige Busfahrt nach Istanbul beginnt. Mir geht es gesundheitlich gar nicht gut. Ich bin sehr fertig, fühle mich schwach, es ist unfassbar unbequem, was gar nicht mal so am Bus liegt. Die Busfahrt zieht sich, am Ende haben wir auch zwei Stunden Verspätung. Ich sag’s wie’s ist: Es ist mehr durchhalten als alles andere. Der YHT (der türkische ICE) hätte nur viereinhalb Stunden gebraucht…

In Istanbul angekommen, nehme ich ein Taxi zum Hostel. Sachen abstellen, liegen, schlafen, endlich.
