---
title: "Rückreise Tag 2: Von Kvariati über Sarpi und Hopa nach Kars"
author: "žuk"
date: "2025-08-"
categories: [Georgien, News]
image: ""
description: ""
draft: true
---

…und früh wieder raus. Als mein Wecker um 6.40 Uhr klingelt, liege ich schon zehn Minuten wach. Früh aufstehen ist einfach nicht meins (und früh ins Bett gehen auch nicht). In wenigen Minuten werde ich Georgien verlassen. Wann ich wiederkomme, weiß ich noch nicht, aber das Land wird sich in der Zeit ganz bestimmt sehr verändern. Es ist wie, wenn man einen Freund x Jahre nicht gesehen haben wird und man weiß, dass er in Pläne hat, die in eine andere Richtung gehen als die, aus der er kommt.

Ich bin um sieben Uhr mit meinem Fahrer verabredet. Ich bin da, der Fahrer nicht. Nach zweimal telefonieren steht er dann um 7.20 Uhr bereit und fährt mich zur Grenze. Jetzt ist es wirklich (gleich) vorbei, denke ich, als ich in die Grenzstation laufe. Leider muss ich mich schon jetzt von einem lebendigen Erinnerungsstück trennen, meinen Drachenfuß darf ich leider nicht in die Türkei einführen, generell keine wurzelnden Pflanzen. Na gut. :(

Nach dem Geldwechsel meiner letzten ლარი (Lari) in türkische Lira suche ich die Marshutka auf, die mich nach Hopa bringen wird. Seit dem letzten Jahr ist der Wert der Lira weiter gefallen. Damals entsprachen 38 Lira einem Euro (19.09.2024), heute sind es 47. In der Marshutka stelle ich fest, dass ich die Zeitumstellung nicht eingerechnet habe und eine Stunde eher als ursprünglich geplant am Busbahnhof sein werde. Heißt dann drei Stunden warten.

An selbigem angekommen komme ich schnell mit Bennett an, wie sich herausstellt ist sie französische Englischlehrerin, hat neun Jahre in Deutschland gelebt und ist vor allem sehr redselig. Das ist schön, denn so vergehen die drei Stunden warten wie im Flug. Sie hat wie ich einen Faible für Züge, außerdem hat sie mir Bilder ihrer Wohnungen gezeigt – meine Güte, ich habe selten so schöne Dekorationen gesehen. Sie hat in Hagen gewohnt, direkt neben dem Bahnhof in einem alten Uhrenturm. Ihr Schlafzimmer war wie ein Schlafwagen gestaltet – genial. Bennett ist laut (sagt sie selbst) und deswegen inkompatibel mit der deutschen Kultur (sagt sie auch selbst). Ich würde das etwas relativer sehen, aber Bennett ist sich für „kontroversere“ Positionen nicht zu schade (und das meine ich ganz positiv). Es macht sehr Spaß ihr zuzuhören und sich mit ihr über Dinge zu amüsieren, zumal sie einfach sehr gutes Englisch spricht. Sie ist sehr offenherzig und wir verstehen uns sehr gut. Interessanterweise erfahre ich von ihr, dass Armenien (basierend vor allem aus ihren Erfahrungen in Gyumri, wo ich mit David auch war) für sie das christliche Afghanistan ist, weil sie noch nie in einem christlichen und gleichzeitig so rückschrittlichen Land bezüglich Frauenrechte war. Es folgten entsprechende, sehr krasse Geschichten: von einer Frau, die mit 40 nicht wusste, dass man sich auch als Frau selbst befriedigen kann. Von zahlreichen fremden Personen, die sie aus heiterem Himmel auf Sex ansprechen. Von einem 24-Jährigen, der geschockt ist, dass eine Frau weiß, dass er sich auch zuhause selbst befriedigen könnte und noch nie in seinem Leben mit einer weiblichen Person über Sexualität gesprochen hat. Und so weiter und so fort.

Die Busfahrt ist dann etwas ruhiger, wir sitzen leider nicht nebeneinander, was aber auch gut zum Pause machen ist. Ich höre Musik und schaue vor allem aus dem Fenster. Das lohnt sich, denn draußen fliegen Landschaften vorbei, die an amerikanische Canyons erinnern. Wunderschön, mit zahlreichen türkisen Stauseen. Dann fange ich den unendlichen Podcast mit dem Filmemacher Wim Wenders an. Auch wenn ich noch nicht ganz durch bin – ich kann die siebeneinhalb Stunden wärmstens empfehlen. Es ist unfassbar spannend, was dieser Mann alles erlebt hat und was er für Geschichten erzählt. „Alles gesagt“ ist, finde ich, vor allem deswegen ein so geniales Format: Weil man so viel über die interviewten Personen erfährt wie nirgendwo anders. Den Podcast gibt’s entweder bei [YouTube](https://www.youtube.com/watch?v=7tm7srfm500), auf der [ZEIT-Website](https://www.zeit.de/kultur/film/2025-08/wim-wenders-interviewpodcast-alles-gesagt) oder im Podcast-Player eurer Wahl.

Schließlich sind wir in Kars. Ganz beseelt vom Wim-Wenders-Podcast bin ich tatsächlich überrascht, warum wir nach sechseinhalb Stunden „schon“ da sind. Einen Tee und den anschließenden Abschied von Bennett, die für drei Nächte bleibt und danach erst den Dogu-Express nimmt, und dann mache ich mich auf zum Hotel. Sachen abstellen, schnell noch mein Busticket für Ankara–Istanbul buchen. Ich hab nämlich erschreckt festgestellt, dass alle Zugtickets schon weg sind für den Tag. So ein Mist, bei Nele hat das (natürlich Off-Season) super gut am selben Tag funktioniert. Dann laufe ich noch hoch zur Festung. Es ist ein schöner lauer Sommerabend und auch wenn ich den Sonnenuntergang knapp verpasse, freue ich mich sehr an dem Licht, in das diese kleine Stadt im Osten der heutigen Türkei gelegen ist. Macht euch gerne selbst ein Bild von ihrer Geschichte ([Service-Link zu Wikipedia](https://de.wikipedia.org/wiki/Kars)), ich bin leider nur viel zu kurz hier, um das grade zu schaffen.

Morgen geht es schon weiter. Ich bin traurig, Georgien zurückzulassen, aber das Reisefieber hat mich schon wieder gepackt. Ich freue mich sehr auf meine Zugfahrt. Auf viele schöne Bilder, die sich mir zeigen würden, und auf einen schönen Schlafwagen, der mir für eine Nacht ein Zuhause sein wird.

Ich mach mich jetzt ins Bett, denn auch morgen geht es wieder früh raus. Habt es gut und bis bald.
