---
title: "RSS-Feed ab jetzt abbonnierbar"
author: "žuk"
date: "2025-08-01"
categories: [News]
image: "https://zukloud.zukarton.eu/apps/files_sharing/publicpreview/rYacHfxicidiT6d?file=/&fileId=147060&x=1920&y=1080&a=true&etag=fc62fd611774125afb9aea1dcac23a90"
description: ""
---

Letztens bin ich auf das Thema RSS-Feeds gestoßen und irgendwie ist das bisher komplett an mir vorbeigegangen. Ich wusste, dass das irgendwie existiert und auch ungefähr, worum es geht, aber konkret hatte ich keinen Plan. Ich gehe sehr autodidaktisch an meine kleineren IT-Projekte wie zum Beispiel diesen Blog heran. Oft fange ich sehr klein an und bin froh, wenn irgendwas läuft, und mit der Zeit entdecke ich immer mehr Details und baue hier und da Features ein oder beginne Dinge mehr zu verstehen.

Nun ja, und jetzt war es Zeit, mich um RSS-Feeds zu kümmern. Das ist passiert und ab heute könnt ihr auch über RSS stets aktuell bleiben und euch benachrichtigen lassen, wenn es hier Neuigkeiten gibt. Das ist mein Link: <https://blog.zukarton.eu/blog.xml>.

Für die, denen RSS bis heute absolut gar nichts sagt, hier eine ganz kurze Einführung, die euch vielleicht schon überzeugt, denn eigentlich ist die Idee ziemlich genial. Keine Sorge, es wird nicht zu technisch, denn im Detail habe ich davon auch keine Ahnung.

RSS ist eine einfache und bewährte Technologie, mit der ihr neue Beiträge einfach automatisch bekommt, ohne dass ihr Internetseiten (z.B. diesen Blog) immer wieder aktualisieren müsst, um zu erfahren, was es neues gibt. Das einzige, was ihr dafür braucht, ist eine RSS-App und den Feed-Link. Meinen Link findet ihr oben und Apps gibt es zahlreiche. Ich empfehle [FeedFlow](https://www.feedflow.dev/), das gibt es für alle Plattformen (Linux, Windows, macOS / Android, iOS), oder die [Integration in Thunderbird](https://blog.thunderbird.net/2022/05/thunderbird-rss-feeds-guide-favorite-content-to-the-inbox/),), bei der Updates aus dem Feed wie neue E-Mails dargestellt werden. Im Programm eurer Wahl gebt ihr einfach nur den Feed-Link ein und schon werdet ihr immer benachrichtigt, wenn im Blog etwas neues erscheint. Außerdem ist RSS gerade bei Blogs ziemlich verbreitet und so könnt ihr kostenfrei, datenschutzfreundlich, ohne Algorithmus und unnötige Interaktionen auf dem Laufenden bleiben.

Ich bin ein bisschen stolz, dass ich das jetzt auch habe (auch wenn es wahrlich keine neue Technologie ist), und hoffe, euch ein bisschen anzustecken. Wir sehen uns im Feed!
