---
title: "Rückreise Tag 3: Von Kars bis irgendwo in der Türkei"
author: "žuk"
date: "2025-08-"
categories: [Georgien, News]
image: ""
description: ""
draft: true
---

Aufstehn, duschen, Taxi zum Bahnhof. Es dauert keine zehn Minuten, schon werde ich von einem armenischen Türken angesprochen. Der Schlafwagen, Nummer 6, ist der letzte des Zuges. Das hat für mich als Eisenbahnromantiker viele Vorteile, weil es in keinem Wagen so tolle Blicke geben wird – auf die Lok und den Rest des Zuges bei Kurven, aber auch auf die Gleise hinter uns. Um 8 Uhr geht es los. Immer wieder springe ich von einem Fenster zum nächsten, mache Fotos oder schaue einfach nur. Ich liebe es sehr, wenn die Lok und die anderen Wagen in Kurven zu sehen sind, und die Strecke des Dogu-Express fügt sich sehr in die Landschaft ein, ist also äußerst kurvenreich und somit prädestiniert für fantastische Blicke und Fotos.

Denn die Landschaft außerhalb des Fensters lohnt sich! Hier jetzt mittendrin das Zelt aufzuschlagen (das ich ja gar nicht mehr habe…), das wäre es jetzt. Aber auch mit meinem Fensterblick bin ich vollständig zufrieden und freue mich sehr an der Aussicht. Es ist völlig anders als in Georgien, wo Hügel, Täler, Wälder viel mehr komprimiert auf kleinere Landstriche sind. Draußen ist alles weit. Trotzdem hügelig, weniger bewaldet, mehr steppenartig, aber vor allem weit. Zwischendurch fühlt es sich auch wieder nach amerikanischen Canyons und Valleys an.

Irgendwann stehen wir länger. Mein „Freund“ (natürlich bin ich nach dem ersten Gespräch schon der neue Freund) vom Gleis vorhin sitzt in Wagen 4, Sitzplatz, Schlafwagen ist zu teuer. Ich gehe ihn besuchen und stelle fest, dass die Türen offen sind. Er weiß Bescheid: Vor uns liegt ein Güterzug, der hat Probleme mit der Lok. Unsere Lok ist losgefahren, um ihm zu helfen. Jetzt stehen wir also im Nirgendwo, ohne Lok vorne oder hinten.

Aber dann geht es doch weiter. Das Reisetempo des Dogu-Expresses ist gemächlich, es gibt viel Zeit, auch kleinere Details in der vorbeiziehenden Landschaft zu entdecken. Zum Beispiel dachte ich vorhin, dass es hier so einige Stellen gab, die deutlich regenbogenfarbener aussahen als die „berühmten“ Rainbow Mountains in [დავით გარეჯა (Davit Gareja)](2024-11-28_zerstreuung.qmd). Über den Namen Express könnte man also durchaus streiten, aber das gilt ja auch für einige Bummelbahnen in Deutschland. Jedenfalls gefällt mir das Tempo sehr und ich genieße die Zeit hier.

Nach dem Zwischenstopp lege ich mich aufs Ohr und schlafe etwas. Dann sitze ich etwas im Bordrestaurant und unterhalte mich mit einigen anderen Passagieren. Wir haben einen neuen Zimmergenossen. Er spricht sogar etwas, wenn auch sehr brüchiges Englisch und wir unterhalten uns ein wenig. Dann bahnt sich der Sonnenuntergang an und die nächste Stunde bin ich mit Schauen und Fotografieren beschäftigt.

Am Abend esse ich etwas von meinen Vorräten und setze mich anschließend ins Bordrestaurant und schreibe ein paar Gedichtfetzen auf. Während ich mich wieder mit meinem Abteilgenossen unterhalte, gesellt sich eine Südafrikanerin zu uns, die vor allem Leute Englisch sprechen gehört hat. Wir unterhalten uns sehr lang über verschiedenste Themen. Sie reist im Moment durch Osteuropa, Kleinasien und Zentralasien und ist eigentlich Privatköchin. Eine sehr interessante Person. Ich merke, dass ich es sehr genieße, mit Leuten noch Englisch sprechen zu können. Hat sich doch einiges getan, in dem Jahr.

Wenig später kommt unser Schaffner zu uns und sagt etwas auf Türkisch. Mein Abteilgenosse versucht zu übersetzen, bei uns kommt nur an: Wir fahren jetzt noch bis Sivas und da sind wir dann noch eine Stunde. Dann müssen alle in Busse umsteigen und wir werden nach Kayseri gefahren, wo wir dann wieder in einen Zug nach Ankara steigen. Na toll. Warum habe ich mir nochmal ein Schlafwagen-Ticket gekauft, wenn wir die Nacht größtenteils im Zug verbringen? Bis nach zwölf unterhalte ich mich noch mit Margreth, so heißt die Südafrikanerin, dann lege ich mich noch etwas aufs Ohr. Nach etwa einer Stunde werden wir rausgescheucht, zu den Bussen. Zwei bis drei Stunden werden wir wohl fahren. Etwa 2.30 Uhr geht es los. Schlafen funktioniert zumindest ganz gut, ich bin auch echt müde. Um 5 Uhr befinden wir uns wieder im Zug (nicht derselbe, aber auch erkennbar ein Dogu-Express), der irgendwann auch losfährt. Eieiei. Mal schauen, wie der morgige Tag wird…
