---
title: "Rückreise Tag 5: Von Istanbul Richtung Bulgarien"
author: "žuk"
date: "2025-08-"
categories: [Georgien, News]
image: ""
description: ""
draft: true
---

Ich schlafe ganz gut, wenn auch nicht sonderlich lang, fühle mich nur mittelmäßig besser. Ich finde es nicht einfach, etwas taugliches zum Essen zu bekommen. Einfach nur Brot, das wär’s. Naja, nur noch wenige Tage, dann bin ich in Deutschland. Ich buche mir einen zusätzlichen Hostel-Tag, damit ich nachmittags noch ausruhen kann.

Um 18 Uhr geht’s zurück, mit leider nur dürftigen, aber den Umständen entsprechendem Essen ausgestattet, mache ich mich – der Anstrengung wegen wieder mit Taxi – auf den Weg zum Bahnhof Istanbul Halkali, wo mein Nachtzug nach Bukarest startet. Alles klappt gut. Am Gleis treffe ich ein nettes französisches Pärchen – es sind allgemein so viele Französ\*innen unterwegs, das überrascht mich sehr, die Türkei gilt doch als ein „deutsches“ Urlaubsland?! Nun ja, in meinem Abteil wohnt auch noch ein französischer Familienvater aus Straßburg, der ins Familienabteil nebenan vermutlich nicht mehr reingepasst hat. Wir unterhalten uns sehr nett, die Familie macht eine Interrail-Rundreise, war auch schon in Berlin und eben auch Istanbul. Jetzt geht’s zurück. Klingt alles sehr hübsch und interessant.

Dann schlafen, gut so, ich bin echt müde. Aber ich fühle mich schon viel besser als heute früh, das ist doch mal ein gutes Zeichen.

Die Grenzkontrolle zwischen der Türkei und Bulgarien kommt um drei Uhr morgens und verläuft wesentlich glimpflicher als erwartet. Wir müssen nicht mit allen Sachen aussteigen und durchleuchtet werden, sondern es erfolgt nur eine einfache Passkontrolle. Ein Glück. So komme ich auf ausreichenden und nur leicht gestörten Schlaf.
