---
title: "Rückreise Tag 6: Von Bulgarien nach Bukarest"
author: "žuk"
date: "2025-08-"
categories: [Georgien, News]
image: ""
description: ""
draft: true
---

Ich fühle mich wieder etwas besser, aber ganz gesund bin ich noch nicht. Aus dem Fenster zu schauen lohnt sich sehr, aber ich ruhe mich auch viel aus, schlafe nochmal etwas. Irgendwann (ich glaube, in der Nacht) wurden wir umgekoppelt, das habe ich halb verpasst. Nun hängt der Zugteil nach Sofia nicht mehr hinter uns, sondern ein bulgarischer Zug (vorher türkischer Nachtzug).

Jetzt kommt das nächste Umkuppeln, wir sind in Ruse, kurz vor der rumänischen Grenze. E-Lok wird ausgetauscht gegen eine Diesellok. Dahinter hängen drei Wagen dreier Bahngesellschaften dreier verschiedener Länder: Wir (türkisch), ein bulgarischer Wagen und ein rumänischer. Weiter geht’s, jetzt über die Donau.

Mit ungefähr anderthalb Stunden Verspätung kommen wir dann in Bukarest an. Hostel, einkaufen (im Kaufland!!), essen. Dann telefoniere ich noch lange mit Nele und geh schlafen.
