---
title: "Rückreise Tag 7: Von Bukarest über Wien nach Dessau"
author: "žuk"
date: "2025-09-"
categories: [Georgien, News]
image: ""
description: ""
draft: true
---

Es ist tatsächlich der letzte Tag meiner langen Reise zurück nach Deutschland. Gestern war es schon ganz absurd, in einem Kaufland in Bukarest einzukaufen und plötzlich all die „gewohnten“ beziehungsweise eben nicht mehr gewohnten Lebensmittel zu sehen. Mein Zug geht um 14.07 Uhr und ich habe einen entspannten Vormittag, kaufe in Ruhe Essen ein, schreibe noch etwas und mache mich dann eine Stunde vor Abfahrt Richtung Bahnhof, der fußläufig nur fünf bis zehn Minuten entfernt ist.

Dort angekommen bin ich erstmal irritiert. Die Gleise werden immer nur zehn bis zwanzig Minuten vorher kommuniziert, das ist verwirrend. Und irgendwie gibt es meinen Zug nicht…

Am Schalter sagt mir die Bahn-Frau, dass ich wohl den Zug um 15.07 Uhr meine, nach Wien. Nun ja, dann wird das wohl der sein, vielleicht gab es einen Fahrplanwechsel? Beim Warten auf die Gleisinformation stehe ich neben zwei Deutschen, die mich aufklären, dass die ÖBB aus mir wirklich vollends unverständlichen Gründen – keine andere Eisenbahngesellschaft, mit der ich gereist bin, hat das so gemacht – österreichische Zeit, also MESZ angibt, obwohl Bukarest eine Stunde später dran ist. 14.07 Uhr ist also MESZ und Ortszeit 15.07 Uhr. Ein Glück, dass die Verschiebung in diese Richtung stattfindet, nicht andersherum…

So habe ich viel Wartezeit und erreiche auch meinen letzten Nachtzug. Es ist gar kein österreichischer, sondern ein rumänischer und er hat diese wunderbaren Fenster, aus denen man sich vollends rauslehnen kann.

Mein Abteil ist sehr international besetzt, wir fangen an mit einem Australier, einem französischen Pärchen und mir, später folgen noch eine Person aus Rumänien (die ein paar sehr wilde Vorstellungen über den Ukraine-Krieg hat) und eine Person aus Österreich. Wie schon zu erahnen sind diese Nachtzüge effizienter gebaut, es passen sechs Personen in eine Kabine, nicht nur vier.

Die ersten ein, zwei Stunden quatschen wir viel. Ich habe sehr viel Freude daran, noch mit Leuten Englisch zu sprechen, bevor ich wieder in einem Land bin, wo mich sowieso jeder rein sprachlich versteht. Und dann ist sogar noch ein Muttersprachler dabei. Mit MJ, so ist sein Name, es sind die Initialen seiner beiden Vornamen, verstehe ich mich gut und er zeigt sich sehr interessiert (und erstaunt über lustige Begebenheiten des Deutschen, zum Beispiel die Wortbildungen mit „Zeug“). Wir haben viel Spaß miteinander und das ist schön.

Und dann müssen wir die Aussicht genießen, denn die Strecke ist einfach u n f a s s b a r schön. Ganz viele Kurven, viele Berge, wundervoller Wald, es ist der westliche Teil Rumäniens und er muss wirklich sehr sehenswert sein. Natürlich mache ich sehr viele tolle Bahnfotos…

Dann wird es Nacht und am nächsten Morgen landen wir in Wien, wo ich noch ein paar Stunden Aufenthalt habe, bis mein ICE, den ich mit großer Pufferzeit wegen Verspätungsgefahr gebucht habe, abfahren wird. Leider ist er nicht frühzeitig komplett verspätet, sonst hätte ich noch einen früheren nehmen können.

So fahre ich über Nürnberg, Halle und Bitterfeld nach Dessau und bin sehr fasziniert davon, wie leise Bahn fahren sein kann. Und so pünktlich – unfassbar. Es ist wirklich lustig, dass ausgerechnet die deutschen Züge auf meinem Hinweg nach Georgien, aber auch auf meinem Rückweg die pünktlichsten waren. Das kann ich nach meiner nächsten Fahrt dann schon nicht mehr behaupten…
