---
title: "Rückreise Tag 1: Von Tsipnari über Batumi nach Kvariati"
author: "žuk"
date: "2025-08-"
categories: [Georgien, News]
image: ""
description: ""
draft: true
---

Meine Zeit in Georgien ist nun vorbei, es fühlt sich seltsam an – natürlich – und traurig bin ich auch darüber. Wehmütig, aber definitiv auch etwas erleichtert. Am Abend vorm Beginn meiner Rückreise telefoniere ich noch mit tux, solange bis mein Internet-Paket ausläuft. Für die letzten Tage hatte ich jeweils unlimited Internet für 24 Stunden, ich hab es jeden Tag vergessen, zu verlängern. Ich schlafe nicht besonders gut, aber auch nicht besonders schlecht. Und tatsächlich wache ich zufällig zum Sonnenaufgang auf, weil ich auf Toilette muss. Mein erster Sonnenaufgang hier, glaube ich, – und mein letzter.

::: callout-note
Ich habe beschlossen, über meine Rückreise mal in etwas anderer Form, weniger retrospektiv zu berichten. Ich bin am 14.08. in წიფნარი (Tsipnari) aufgebrochen und werde am 21.08. in Dessau ankommen. So, damit sind die zeitlichen Klarheiten hoffentlich beseitigt.
:::

Als der Tag dann richtig losgeht, geht alles recht fix. Zähneputzen, letzte Sachen zusammenpacken, mit dem Auto die 50 Meter zur Marshutka-Haltestelle fahren (aufgrund meines zahlreichen Gepäcks sogar ausnahmsweise angebracht), mich von Saleko und Tornike verabschieden, წიფნარი (Tsipnari) war quasi schon gestern Abend dran. Die letzten Male გურია (Guria) bewundern, seine grünen Wälder in mehr Grüntönen als ich benennen könnte, seine kleinen Felder und Hügelketten, die gewundenen Straßen, an sich angerostete Gasleitungen schmiegen, die vielen lieben Straßenhunde, die sich so sehr über Gesellschaft freuen. Es ist ein trauriger Abschied, aber ich bin auch sehr glücklich, dieses Paradies auf Erden – denn das ist es! – kennengelernt und, ermöglicht durch Levan und Saleko, relativ untouristisch erschlossen zu haben. Ich bin wirklich traurig, წიფნარი (Tsipnari), გურია (Guria), საქართველო (Georgien) hinter mir zu lassen. Ich werde vieles vermissen.

Die Marshutka fährt erst nach ჩოხატაური (Chokhatauri), fast alle steigen dort aus, kleine Pause, zwei heiße ლობიანი (Lobiani) kaufen – es werden die letzten für mich sein, schluchz! Einsteigen, weiter geht’s nach ბათუმი (Batumi). Nachdem wir das traumhafte გურია (Guria) verlassen haben, schlafe ich etwas und wache kurz vor ბათუმი (Batumi) wieder auf.

In ბათუმი (Batumi) holt mich მალხაზი (Malkhazi) ab, ein Freund Salekos. Er fährt mich nach კვარიათი (Kvariati), zwei Kilometer vor სარფი (Sarpi), die Grenzstadt zur Türkei. Dort habe ich ein Zimmer in einer Hütte. Blick aufs Meer. Tasche abstellen, dann etwas Essen gehen. Zum letzten Mal ხინკალი (Khinkali) essen und ნატახტარი (Natakhtari), mein liebstes georgisches Bier, trinken. Danach huppe ich ins Schwarze Meer, diesmal auch zum letzten, aber vor allem zum ersten Mal. Der Strand ist völlig überfüllt, einen ganzen Tag könnte ich das nicht ertragen. Das Wasser ist sehr warm (und wer mich kennt, der\*die weiß, dass ich eigentlich eher eine Frostbeule bin) und ich koste es sehr aus, im Meer schwimmen zu können. Am Abend telefoniere ich noch mit meinen Eltern und genieße den phänomenalen Sonnenuntergang. Auf jeden Fall ein gebührender Abschluss dieses Jahres. Und dann geht’s früh ins Bett…
