---
title: "In eigener Sache…"
author: "žuk"
date: "2025-01-25"
categories: [Politik]
#image: ""
description: ""
---

Wer die CDU wählt, könnte die AfD mitwählen. Denn die „Brandmauer“ der CDU gegen die AfD gibt es nicht mehr. CDU-Generalsekretär Carsten Linnemann, der erste Mann hinter Merz, ließ von sich verlauten: „Das Nazi-Bashing gegen die AfD muss aufhören“. Das soll den Weg für eine Kooperation von AfD und CDU für Antimigrationspläne im Bundestag freimachen, die an sich mal wieder (wie fast alle derzeitigen Pläne bezüglich Migration) völlig an der Sache vorbeigehen. Aber ganz abgesehen davon: Es gibt kein Nazi-Bashing gegen die AfD, denn die AfD *ist* eine Nazi-Partei, rechtsextrem, rechtspopulistisch und genauso gefährlich wie ihr ideologisches Vorbild, die NSDAP. Geschichte wiederholt sich nicht, aber deutliche Parallelen gibt es trotzdem. Will die CDU mit den Nazis Hand in Hand gehen, wenn diese unsere freiheitlich demokratische Grundordnung abschaffen werden? Ich denke, die Tendenzen sind klar und eindeutig – und mittlerweile auch im Bundesvorstand angekommen, in Sachsen-Anhalt beispielsweise grassieren diese Ideen schon viel länger.

**Wer die Demokratie stärken will, darf also sein Kreuz nicht bei der AfD oder der CDU machen**, denn letztere paktiert im Zweifel gerne mit den Rechtsextremen und Neofaschisten, wenn es ihr politisch in den Kram passt.

Geschichte wiederholt sich nicht, aber wir können aus ihr lernen. Und eine der wichtigsten Lehren sollte sein: Mit Rechtsextremen und Faschist\*innen paktiert man nicht. Wer die CDU wählt, wählt die AfD mit. Wenn wir in zehn Jahren amerikanische, österreichische oder ungarische Verhältnisse haben, dann sind auch diejenigen Schuld, die jetzt die Augen zugemacht haben, Steigbügelhalter gewählt haben oder sich von einer Zeitung mit vier sehr großen Buchstaben haben diktieren lassen, was angeblich die Probleme dieses Landes seien.

Wählt bitte *irgendeine* vernünftige Partei. Die Grünen, die SPD, die Linken oder in Gottes Namen auch die FDP (auch wenn die es sicher gar nicht verdient hat). Aber macht euer Kreuz bloß nicht bei der Wir-kooperieren-auch-gerne-mit-Nazis-Partei CDU oder den Rechtsextremen von der AfD.[^1]

[^1]: Kooperation fängt indirekt an – mit dem bewussten In-Kauf-nehmen, Anträge nur mit Hilfe von AfD-Stimmen beschließen zu können. Auch wenn Merz – vermutlich zurecht – sagt, es gäbe keine Absprachen. Das ist der Anfang…

Und vergessen wir nicht: Die CDU macht die AfD gerade so stark, weil sie das Migrationsthema immer mehr pusht. Diese Partei tut unserer Demokratie nicht gut. Wählt was vernünftiges. Bitte.

Es ist eine krasse Zeit, die geprägt ist von lauter Grenzüberschreitungen und irrsinnigen Debatten, die nichts mehr mit der Realität zu tun haben (Stichwort Migration, Sicherheit, …). Und es klingt absurd (und ist natürlich vor allem emotional), aber ich merke, wie ich in den letzten Wochen das erste Mal in meinem Leben den Gedankengang hatte: Was würde die AfD eigentlich „schlechtes“ über mich im Internet finden, wenn sie auf der Suche nach den unbequemen Leuten ist? Ja, wir sind noch weit weg davon und wir leben nicht in der Weimarer Republik. Aber es ist kein ausgeschlossenes Szenario mehr, so wie ich das vor fünf, sechs Jahren gesagt hätte. Und versteht mich nicht falsch, rational bin ich sehr weit weg davon, dass ich mich aus zukünftlicher Angst nicht öffentlich kritisch äußern würde, sonst würde ich das hier nicht schreiben, *aber*: Es ist ganz schön furchtbar, dass emotional die Angst da ist.

Aus diesem Grunde: Stellt euch dagegen, wenn ihr es schafft (auch das ist sehr wichtig!). Widersprecht, seid empathisch oder was es auch immer braucht. Aber bleibt nicht still, bitte! Es ist so, so, so wichtig. Es ist nicht wichtig, weil wir eine besondere Vergangenheit haben, es ist wichtig, damit wir keine besondere Zukunft haben.
